# Generated by Django 5.0.6 on 2026-06-05 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=100, verbose_name='รหัสสินค้า (JST)')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='ชื่อสินค้า (cached)')),
                ('status', models.CharField(choices=[('รอดำเนินการ', 'รอดำเนินการ'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('เรียบร้อย', 'เรียบร้อย')], default='รอดำเนินการ', max_length=20, verbose_name='สถานะ')),
                ('assignee', models.CharField(blank=True, max_length=100, verbose_name='ผู้รับผิดชอบ')),
                ('process_date', models.DateField(blank=True, null=True, verbose_name='วันที่ดำเนินการ')),
                ('done_date', models.DateField(blank=True, null=True, verbose_name='วันที่เรียบร้อย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'สินค้าโล๊ะ',
                'verbose_name_plural': 'สินค้าโล๊ะ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClearancePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.CharField(blank=True, max_length=255, verbose_name='ราคาเดิม')),
                ('new_price', models.CharField(blank=True, max_length=255, verbose_name='ราคาใหม่ (ลดล้างสต็อก)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='clearance.clearanceproduct')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
