# Generated by Django 5.0.6 on 2026-06-05 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producttest', '0002_rename_pang_to_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ชื่อประเภทสื่อ')),
                ('category', models.CharField(choices=[('video', 'งานคลิป'), ('image', 'งานรูปภาพ')], default='video', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ประเภทสื่อ',
                'verbose_name_plural': 'ประเภทสื่อ',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GraphicJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('image', models.ImageField(blank=True, null=True, upload_to='graphicqueue/products/', verbose_name='รูปสินค้า')),
                ('status', models.CharField(choices=[('รอดำเนินการ', 'รอดำเนินการ'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('เรียบร้อย', 'เรียบร้อย')], default='รอดำเนินการ', max_length=20, verbose_name='สถานะ')),
                ('urgency', models.CharField(choices=[('ทั่วไป', 'ทั่วไป'), ('ด่วน', 'ด่วน')], default='ทั่วไป', max_length=10, verbose_name='ประเภทงาน')),
                ('product_type', models.CharField(choices=[('สินค้าเทส', 'สินค้าเทส'), ('สินค้าเก่า', 'สินค้าเก่า')], default='สินค้าเทส', max_length=20, verbose_name='ประเภทสินค้า')),
                ('order_date', models.DateField(verbose_name='วันที่สั่งงาน')),
                ('deadline', models.DateField(verbose_name='วันเดดไลน์')),
                ('submit_date', models.DateField(blank=True, null=True, verbose_name='วันที่ส่งงาน')),
                ('work_url', models.CharField(blank=True, max_length=1000, verbose_name='URL ลิ้งค์ส่งงาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_graphic': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graphic_jobs', to='producttest.employee', verbose_name='ผู้รับผิดชอบ')),
                ('media_types', models.ManyToManyField(blank=True, related_name='jobs', to='graphicqueue.mediatype', verbose_name='สื่อที่ต้องการทำ')),
            ],
            options={
                'verbose_name': 'คิวงานกราฟฟิก',
                'verbose_name_plural': 'คิวงานกราฟฟิก',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='graphicqueue/refs/')),
                ('brief', models.TextField(blank=True, verbose_name='Brief อธิบายรูป')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_images', to='graphicqueue.graphicjob')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
