# Generated by Django 5.0.6 on 2026-09-30 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'หมวดหมู่เพจ',
                'verbose_name_plural': 'หมวดหมู่เพจ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='pagemanager.pagecategory', verbose_name='หมวดหมู่'),
        ),
        migrations.CreateModel(
            name='PageStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, verbose_name='SKU')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='pagemanager.facebookpage')),
            ],
            options={
                'verbose_name': 'รายการ STOCK',
                'verbose_name_plural': 'รายการ STOCK',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='เดือน')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ADS (฿)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='pagemanager.facebookpage')),
            ],
            options={
                'verbose_name': 'ADS รายเดือน',
                'verbose_name_plural': 'ADS รายเดือน',
                'ordering': ['-month'],
                'unique_together': {('page', 'month')},
            },
        ),
    ]
