# Generated by Django 5.0.6 on 2026-06-04 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ยอดรวมค่าคอม')),
                ('per_person', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ค่าคอมต่อคน')),
                ('status', models.CharField(choices=[('รอกรอกค่าคอม', 'รอกรอกค่าคอม'), ('รอจ่ายค่าคอม', 'รอจ่ายค่าคอม'), ('จ่ายค่าคอมเรียบร้อย', 'จ่ายค่าคอมเรียบร้อย')], default='รอกรอกค่าคอม', max_length=30, verbose_name='สถานะค่าคอม')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='หมายเหตุ')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slips/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='producttest.commission')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_graphic', models.BooleanField(default=False)),
                ('is_mkt', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=50, unique=True, verbose_name='Product ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('info', models.TextField(blank=True, verbose_name='ข้อมูลสินค้า')),
                ('detail', models.TextField(blank=True, verbose_name='รายละเอียดการทำงาน / หมายเหตุ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('upload_date', models.DateField(verbose_name='วันที่ลงข้อมูล')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่มทดสอบ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดทดสอบ')),
                ('manual_status', models.CharField(blank=True, choices=[('', 'อัตโนมัติ (ระบบจัดการ)'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('Test ผ่าน', 'Test ผ่าน'), ('Test ไม่ผ่าน', 'Test ไม่ผ่าน'), ('ยกเลิก', 'ยกเลิก')], default='', max_length=30, verbose_name='สถานะ (ปรับโดยหัวหน้า)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graphic_members', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'is_graphic': True}, related_name='graphic_products', to='producttest.employee', verbose_name='Graphic')),
                ('mkt_members', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'is_mkt': True}, related_name='mkt_products', to='producttest.employee', verbose_name='MKT')),
            ],
            options={
                'ordering': ['-upload_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='ราคาทดสอบ')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='producttest.testproduct')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pang', models.CharField(blank=True, max_length=255, verbose_name='PANG')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='producttest.testproduct')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.PositiveIntegerField(default=0, verbose_name='จำนวนออเดอร์')),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ยอดขาย')),
                ('ads', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ค่าโฆษณา')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='กำไร')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='producttest.testproduct')),
            ],
        ),
        migrations.AddField(
            model_name='commission',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='producttest.testproduct'),
        ),
    ]
