# Generated by Django 5.0.6 on 2026-06-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='pang',
        ),
        migrations.AddField(
            model_name='productpage',
            name='page',
            field=models.CharField(blank=True, max_length=255, verbose_name='PAGE'),
        ),
    ]
