# Generated by Django 5.0.6 on 2026-06-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttest', '0003_employee_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testproduct',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มทดสอบ'),
        ),
    ]
